version: "3.5"

services:
           
    conan-developer:
        container_name: conan-training
        build:
            dockerfile: Dockerfile
            context: .
        command: tail -f /dev/null
