sudo: false
language: python
dist: trusty

jobs:
  fast_finish: true
  include:

    - stage: Linux - Conan Current
      name: Python 3.5
      python: 3.5
      env: TOXENV=py35-conancurrent
      dist: xenial
    - name: Python 3.8
      python: 3.8
      env: TOXENV=py38-conancurrent
      dist: xenial


install:
  - pip install --upgrade pip
  - pip install tox tox-venv tox-travis

script:
  - tox
